#prefix used to show up metrics in AppDynamics
#metricPrefix: "Custom Metrics|Solr"

#This will create it in specific Tier. Replace <TIER_ID>
metricPrefix: "Server|Component:<COMPONENT_ID>|Custom Metrics|Spark Monitor|"

#Add your spark history servers here
servers:
   - host: "localhost"
     port: 18080
     name: "Spark Master"


numberOfThreads: 5

metrics:
     jobs:
        - numTasks:
            alias: "Number of tasks in the application"
            multiplier: "2"
            cluster: "SUM"
            aggregation: "AVERAGE"
            time: "INDIVIDUAL"
        - numActiveTasks:
            alias: "Number of active tasks in the application"
            multiplier: "2"
            cluster: "sum"
            aggregation: "average"
            time: "individual"
        - numCompletedTasks:
