# Copyright 2018. AppDynamics LLC and its affiliates.
# All Rights Reserved.
# This is unpublished proprietary source code of AppDynamics LLC and its affiliates.
# The copyright notice above does not evidence any actual or intended publication of such source code.



#This will publish metrics to one tier (highly recommended)
#Instructions on how to retrieve the Component ID can be found in the Metric Path section of https://docs.appdynamics.com/display/PRO42/Build+a+Monitoring+Extension+Using+Java
#For Controllers 4.2.10+, you can also use the tier name instead of the component ID.
metricPrefix: "Server|Component:<COMPONENT_ID>|Custom Metrics|Spark Monitor|"

#Add your Spark History Servers here. Please refer to the extension docs for Spark history & event logging configuration details.
servers:
   - host: ""
     port:
     name: ""


#Generic metric prefix used to show metrics in AppDynamics (not recommended)
#metricPrefix: "Custom Metrics|Spark"

numberOfThreads: 5

## This section can be used to configure metrics published by the extension. You have the ability to add multipliers & modify the metric qualifiers for each metric.
## Valid 'cluster' rollup values: INDIVIDUAL, COLLECTIVE
## Valid 'aggregation' types: AVERAGE, SUM, OBSERVATION
## Valid 'time' rollup types: AVERAGE, SUM, CURRENT
## You can choose to not add any or all of these fields to any metric and the default values for each of the above will be used (INDIVIDUAL, AVERAGE & AVERAGE for cluster, aggregation & time respectively).
metrics:
     jobs:
        - numTasks:
            alias: "numTasks"  #Number of tasks in the application
            multiplier: "1.0"
            cluster: "INDIVIDUAL"
            aggregation: "AVERAGE"
            time: "SUM"
            delta: "false"
        - numCompletedTasks:
            alias: "numCompletedTasks"  #Number of completed tasks in the application
            multiplier: ""
        - numSkippedTasks:
            alias: "numSkippedTasks"  #Number of completed tasks in the application"
            multiplier: ""
        - numFailedTasks:
            alias: "numFailedTasks"  #Number of completed tasks in the application
            multiplier: ""
        - numActiveStages:
            alias: "numActiveStages"  #Number of active stages
            multiplier: ""
        - numCompletedStages:
            alias: "numCompletedStages"  #Number of completed stages
            multiplier: ""
        - numSkippedStages:
            alias: "numSkippedStages"  #Number of completed stages"
            multiplier: ""
        - numFailedStages:
            alias: "numFailedStages"  #Number of failed stages"
            multiplier: ""

     stages:
        - numActiveTasks:
            alias: "numActiveTasks"  #Number of active tasks in the application's stages
            multiplier: ""
        - numCompleteTasks:
            alias: "numCompleteTasks"  #Number of complete tasks in the application's stages
            multiplier: ""
        - numFailedTasks:
            alias: "numCompleteTasks"  #Number of failed tasks in the application's stages
            multiplier: ""
        - executorRunTime:
            alias: "executorRunTime"  #Time spent by executor in the application's stages (ms)
            multiplier: ""
        - inputBytes:
            alias: "inputBytes"  #Input bytes in the application's stages
            multiplier: ""
        - inputRecords:
            alias: "inputRecords"  #Input records in the application's stages
            multiplier: ""
        - outputBytes:
            alias: "outputBytes"  #Output bytes in the application's stages
            multiplier: ""
        - outputRecords:
            alias: "outputRecords"  #Output records in the application's stages
            multiplier: ""
        - shuffleReadBytes:
            alias: "shuffleReadBytes"  #Number of bytes read during a shuffle in the application's stages
            multiplier: ""
        - shuffleReadRecords:
            alias: "shuffleReadRecords"  #Number of records read during a shuffle in the application's stages
            multiplier: ""
        - shuffleWriteBytes:
            alias: "shuffleReadRecords"  #Number of bytes written during a shuffle in an application's stages
            multiplier: ""
        - shuffleWriteRecords:
            alias: "shuffleWriteRecords"  #Number of shuffled records in the application's stages
            multiplier: ""
        - memoryBytesSpilled:
            alias: "memoryBytesSpilled"  #Number of bytes spilled to disk in the application's stages
            multiplier: ""
        - diskBytesSpilled:
            alias: "diskBytesSpilled"  #Max size on disk of the spilled bytes in the application's stages
            multiplier: ""

     executors:
        - rddBlocks:
            alias: "rddBlocks"  #Number of persisted RDD blocks in the application's executors
            multiplier: ""
        - memoryUsed:
            alias: "memoryUsed" #Amount of memory used for cached RDDs in the application's executors
            multiplier: ""
        - diskUsed:
            alias: "diskUsed" #Amount of disk space used by persisted RDDs in the application's executors
            multiplier: ""
        - activeTasks:
            alias: "activeTasks" #Number of active tasks in the application's executors
            multiplier: ""
        - failedTasks:
            alias: "failedTasks" #Number of failed tasks in the application's executors
            multiplier: ""
        - completedTasks:
            alias: "completedTasks" #Number of completed tasks in the application's executors
            multiplier: ""
        - totalTasks:
            alias: "totalTasks" #Total number of tasks in the application's executors
            multiplier: ""
        - totalDuration:
            alias: "totalDuration" #Time spent by the application's executors executing tasks (ms)
            multiplier: ""
        - totalInputBytes:
            alias: "totalInputBytes" #Total number of input bytes in the application's executors
            multiplier: ""
        - totalShuffleRead:
            alias: "totalShuffleRead" #Total number of bytes read during a shuffle in the application's executors
            multiplier: ""
        - totalShuffleWrite:
            alias: "totalShuffleWrite"  #Total number of shuffled bytes in the application's executors
            multiplier: ""
        - maxMemory:
            alias: "maxMemory" #Maximum memory available for caching RDD blocks in the application's executors
            multiplier: ""

     rdd:
        - numPartitions:
            alias: "numPartitions" #Number of persisted RDD partitions in the application/second
            multiplier: ""
        - numCachedPartitions:
            alias: "numCachedPartitions" #Number of in-memory cached RDD partitions in the application/second
            multiplier: ""
        - memoryUsed:
            alias: "memoryUsed" #Amount of memory used in the application's persisted RDDs
            multiplier: ""
        - diskUsed:
            alias: "diskUsed"  #Amount of disk space used by persisted RDDs in the application
            multiplier: ""
